name: "Docker"
on:
  push:
    branches:
      - develop

  pull_request:
    branches:
      - main

jobs:
  build:
    name: Build Docker
    runs-on: ubuntu-latest

    steps:
      - name: Login to Docker Hub
        uses: docker/login-action@v3
        with:
          username: ${{secrets.DOCKER_USERNAME}}
          password: ${{secrets.DOCKER_PASSWORD}}

      - name: Build the Docker image
        run: docker build . --file Dockerfile --tag pedrovcorsino/tech_challenge:$(date +%s)

      - name: Publish Image to Docker Hub
        run: docker push pedrovcorsino/tech_challenge:latest