name: "Docker"
on:
  push:
    branches:
      - develop

  pull_request:
    branches:
      - main

jobs:
  build:
    name: Build Docker
    runs-on: ubuntu-latest

    steps:
      - name: Login to Docker Hub
        uses: docker/login-action@v3
        with:
          username: ${{secrets.DOCKER_USERNAME}}
          password: ${{secrets.DOCKER_PASSWORD}}

      - name: Build Docker Image
        uses: docker/build-push-action@v2
        with:
          context: app/
          file: Dockerfile
          tags: pedrovcorsino:latest

      - name: Publish Image to Docker Hub
        run: docker push pedrovcorsino/tech_challenge:latest